services:
  - type: worker
    name: zipbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python upload_files.py
    repo: https://github.com/sholoomail/zipbot.git
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: SESSION_NAME 
        value: zipbot
